apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-app
  template:
    metadata:
      labels:
        app: techno-app
    spec:
      containers:
        - name: techno
          image: 
          ports:
            - containerPort: 2000       
           
---
apiVersion: v1
kind: Service
metadata:
  name: techno-app-service
spec:
  selector:
    app: techno-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
  type: LoadBalancer
